import cv2
import numpy as np
import math

# --- MANUAL OBJ WRITER (No Libraries, No Crashes) ---
class ObjWriter:
    def __init__(self):
        self.vertices = []
        self.faces = []
        self.vertex_count = 0

    def add_cube(self, p1, p2, height, thickness=12, z_offset=0):
        """
        Manually calculates the 8 corners of a wall segment 
        and adds them to the 3D object list.
        """
        # 1. Math to find the corners
        dx = p2[0] - p1[0]
        dy = p2[1] - p1[1]
        length = math.sqrt(dx*dx + dy*dy)
        if length < 1: return # Skip noise

        # Perpendicular vector for thickness
        # (normalized vector * thickness/2)
        nx = -dy / length * (thickness / 2)
        ny = dx / length * (thickness / 2)

        # 2. Define the 8 Corners (Vertices)
        # z_bottom = z_offset
        # z_top = z_offset + height
        
        # Bottom 4 corners
        v1 = [p1[0] + nx, p1[1] + ny, z_offset]
        v2 = [p1[0] - nx, p1[1] - ny, z_offset]
        v3 = [p2[0] - nx, p2[1] - ny, z_offset]
        v4 = [p2[0] + nx, p2[1] + ny, z_offset]

        # Top 4 corners
        v5 = [p1[0] + nx, p1[1] + ny, z_offset + height]
        v6 = [p1[0] - nx, p1[1] - ny, z_offset + height]
        v7 = [p2[0] - nx, p2[1] - ny, z_offset + height]
        v8 = [p2[0] + nx, p2[1] + ny, z_offset + height]

        # Add to list
        start_idx = self.vertex_count + 1 # OBJ files start at 1
        self.vertices.extend([v1, v2, v3, v4, v5, v6, v7, v8])
        self.vertex_count += 8

        # 3. Define the 6 Faces (12 Triangles)
        # Each face is a list of vertex indices
        # Bottom
        self.faces.append([start_idx, start_idx+2, start_idx+1])
        self.faces.append([start_idx, start_idx+3, start_idx+2])
        # Top
        self.faces.append([start_idx+4, start_idx+5, start_idx+6])
        self.faces.append([start_idx+4, start_idx+6, start_idx+7])
        # Sides...
        self.faces.append([start_idx, start_idx+1, start_idx+5])
        self.faces.append([start_idx+1, start_idx+4, start_idx+5]) # Front
        
        self.faces.append([start_idx+1, start_idx+2, start_idx+6])
        self.faces.append([start_idx+2, start_idx+5, start_idx+6]) # Right
        
        self.faces.append([start_idx+2, start_idx+3, start_idx+7])
        self.faces.append([start_idx+2, start_idx+7, start_idx+6]) # Back
        
        self.faces.append([start_idx+3, start_idx, start_idx+4])
        self.faces.append([start_idx+3, start_idx+4, start_idx+7]) # Left

    def save(self, filepath):
        with open(filepath, 'w') as f:
            f.write("# Generated by FloorPlan.AI\n")
            f.write("o FloorPlan\n")
            for v in self.vertices:
                # Flip Z and Y for correct orientation in Three.js
                f.write(f"v {v[0]:.2f} {v[2]:.2f} {v[1]:.2f}\n")
            for face in self.faces:
                f.write(f"f {face[0]} {face[1]} {face[2]}\n")

def process_image_to_3d(image_path, output_path):
    print(f"Fn DEBUG: Processing {image_path}")
    
    img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    _, binary = cv2.threshold(img, 200, 255, cv2.THRESH_BINARY_INV)

    kernel = np.ones((3,3), np.uint8)
    binary = cv2.morphologyEx(binary, cv2.MORPH_OPEN, kernel, iterations=1)
    
    # Skeletonize
    dist_transform = cv2.distanceTransform(binary, cv2.DIST_L2, 5)
    _, skeleton = cv2.threshold(dist_transform, 5, 255, cv2.THRESH_BINARY)
    skeleton = skeleton.astype(np.uint8)

    contours, _ = cv2.findContours(skeleton, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
    
    # Initialize our Manual Writer
    writer = ObjWriter()
    
    # Add Floor (Huge flat box)
    h, w = img.shape
    writer.add_cube([0,0], [w,h], 1, thickness=1, z_offset=-1)

    wall_height = 50 # Scaled for visibility
    header_height = 15
    door_height = 35
    
    all_points = []

    # --- BUILD WALLS ---
    for cnt in contours:
        epsilon = 0.005 * cv2.arcLength(cnt, False)
        approx = cv2.approxPolyDP(cnt, epsilon, False)
        points = approx.squeeze()
        if len(points.shape) < 2: continue

        for i in range(len(points) - 1):
            p1 = points[i]
            p2 = points[i+1]
            all_points.append(p1)
            all_points.append(p2)
            
            # Add Wall Segment
            writer.add_cube(p1, p2, wall_height, thickness=8)

    # --- DETECT DOORS ---
    if len(all_points) > 2:
        pts = np.array(all_points)
        for i in range(0, len(pts), 2):
            if i > 500: break 
            for j in range(i + 1, len(pts), 2):
                p1 = pts[i]
                p2 = pts[j]
                
                dist = math.sqrt((p1[0]-p2[0])**2 + (p1[1]-p2[1])**2)
                
                if 25 < dist < 90:
                    # Add Header (Floating Box)
                    writer.add_cube(p1, p2, header_height, thickness=8, z_offset=door_height)

    # Convert output path to .obj if it isn't already
    # The frontend expects a file, usually .glb, but three.js loads .obj too
    # We will rename the file extension in Python to be safe
    final_path = output_path
    if not output_path.endswith('.obj'):
        final_path = output_path + ".obj"
    
    writer.save(final_path) # Save as whatever filename was requested
    print(f"✅ 3D Model generated: {final_path}")